main/urls.py
from django.urls import path
from .views import add_user, add_course, select_user, select_courses, view_table, show_recommendations, matrix

app_name = 'main'
urlpatterns = [
    path('create_user/', add_user, name='new_user'),
    path('create_course/', add_course, name='new_course'),
    path('select_user/', select_user, name='select_user'),
    path('select_courses/<str:username>/', select_courses, name='select_courses'),
    path('table/', view_table, name='view_table'),
    path('recomm/', show_recommendations, name='show_recommendations_list'),
    path('recomm/<str:username>/', show_recommendations, name='show_recommendations'),
    path('matrix/', matrix, name='matrix'),
    path('matrix/<str:username1>/', matrix, name='matrix1')
]

recommendations/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda r: redirect('/app/select_user/')),
    path('admin/', admin.site.urls),
    path('app/', include('main.urls'))
]

main/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=30, unique=True)
    courses = models.ManyToManyField(through='Choice', to='Course', related_name='users')

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Choice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='choices')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='choices')

main/views.py
from django.db.utils import IntegrityError
from django.shortcuts import render, redirect

from main.models import User, Choice, Course
from .utils import get_recommendations_list, get_courses_for_selecting, calculate_djakarta


def add_user(request):
    if request.method == 'POST':
        try:
            user = User.objects.create(name=request.POST['name'])
        except IntegrityError:
            return render(request, 'add_user.html', {'error_mess': 'Пользователь уже существует!'})
        return redirect('main:select_courses', user.name)
    return render(request, 'add_user.html')


def add_course(request):
    if request.method == 'POST':
        try:
            Course.objects.create(name=request.POST['name'])
        except IntegrityError:
            return render(request, 'add_course.html', {'error_mess': 'Курс уже существует!'})
        return render(request, 'add_course.html', {'mess': 'Курс успешно сохранен'})
    return render(request, 'add_course.html')


def select_user(request):
    context = {'users': User.objects.all()}

    if request.method == 'GET':
        return render(request, 'select_user.html', context)

    if request.method == 'POST':
        try:
            user = User.objects.get(name=request.POST['name'])
        except User.DoesNotExist:
            context['error_mess'] = 'Пользователь не существует!'
            return render(request, 'select_user.html', context)
        return redirect('main:select_courses', user.name)


def select_courses(request, username):
    user = User.objects.get(name=username)

    selected_cources_ids = Choice.objects.filter(user=user).values_list('course_id', flat=True)

    context = {
        'username': username,
        'selected_cources_ids': selected_cources_ids,
        'courses': get_courses_for_selecting(selected_cources_ids),
    }

    if request.method == 'POST':
        selected_cources_ids = request.POST.getlist('selected_courses')
        courses = Course.objects.filter(id__in=selected_cources_ids)

        # если не совпадает, значит в списке есть курсы, которых у нас в базе нет => пришли говноданные
        if len(courses) == len(selected_cources_ids):
            Choice.objects.filter(user=user).delete()
            for course in courses:
                Choice.objects.create(user=user, course=course)
                print('Saved: {}'.format(course.name))

        context['mess'] = 'Данные успешно сохранены'

    return render(request, 'select_course.html', context)


def view_table(request):
    return render(request, 'result_table.html', {
        'users': User.objects.all(),
        'courses': Course.objects.all(),
    })


def show_recommendations(request, username=None):
    if username is None:
        context = {'users': User.objects.all()}
    else:
        recommendations = get_recommendations_list(username)

        context = {
            'username': username,
            'recommendations': recommendations,
        }

        if recommendations is None:
            context.update({'error_mess': 'Такого пользователя не существует!'})

    return render(request, 'recommendations_list.html', context)


def matrix(request, username1=None):
    context = {'username1': username1}

    if username1 is not None:
        res = []
        user1_courses = Choice.objects.filter(user__name=username1).values_list('course__name', flat=True)
        for user in User.objects.exclude(name=username1):
            res.append({
                'username1': username1,
                'username2': user.name,
                'user1_courses': user1_courses,
                'user2_courses': Choice.objects.filter(user__name=user.name).values_list('course__name', flat=True),
                'coef': round(calculate_djakarta(username1, user.name), 4)
            })
        context['result'] = res
    else:
        context['users'] = User.objects.all()

    return render(request, 'matrix.html', context)

main/templates/add_course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Course</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/add_course.css' %}">
</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>Добавить курс</h4>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="error">
                        {% if error_mess %}
                            <div id="bs-danger" class="alert alert-danger">
                                <strong>Внимание!</strong> {{ error_mess }}
                            </div>
                        {% endif %}
                    </div>
                    <form class="form-row" method="post" action="{% url 'main:new_course' %}">
                        {% csrf_token %}

                        <h5 for="exampleInputEmail1" style="color:white;">Название курса</h5>
                        <input type="text" class="form-control" id="exampleInputEmail1"
                               aria-describedby="emailHelp" placeholder="Введите название курса"
                               name="name">

                        <input type="submit" id="calculate" class="btn btn-md btn-warning" value="Сохранить">

                    </form>

                </div>
                <div class="col-lg-6">

                </div>
            </div>

            <div class="mess">
                {% if mess %}
                    <div id="bs-success" class="alert alert-success">
                        {{ mess }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

main/templates/add_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New User</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/add_user.css' %}">

</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>Добавить пользователя</h4>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="error">
                        {% if error_mess %}
                            <div id="bs-danger" class="alert alert-danger">
                                <strong>Внимание!</strong> {{ error_mess }}
                            </div>
                        {% endif %}
                    </div>
                    <form class="form-row" method="post" action="{% url 'main:new_user' %}">
                        {% csrf_token %}

                        <h5 for="exampleInputEmail1" style="color:white;">Имя пользователя</h5>
                        <input type="text" class="form-control" id="exampleInputEmail1"
                               aria-describedby="emailHelp" placeholder="Введите имя пользователя"
                               name="name">

                        <input type="submit" id="calculate" class="btn btn-md btn-warning" value="Сохранить">

                    </form>

                </div>
                <div class="col-lg-6">

                </div>
            </div>


        </div>

    </div>
</div>
</body>
</html>

main/templates/common/navbar.html
<nav class="navbar navbar-expand-md navbar-dark ">
    <a class="navbar-brand" href="/">Рекомендательная система курсов</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:new_course' %}">Создать курс</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:new_user' %}">Добавить пользователя</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:view_table' %}">Таблица</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:matrix' %}">Матрица близости</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:show_recommendations_list' %}">Рекомендации</a>
            </li>
        </ul>
        <ul class="navbar-nav" style="float: right;">
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:select_user' %}">Войти</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/matrix.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Matrix</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/select_course.css' %}">
    <style>
        .white {
            color: white;
        }
    </style>
</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>
                Матрица совместимости -
                {% if username1 is none %}
                    выбор пользователя
                {% else %}
                    {{ username1 }}
                {% endif %}
                <a href="{% url 'main:matrix' %}" class="btn btn-sm btn-primary" style="float: right;">Выбрать пользователей</a>
            </h4>
        </div>

        <div class="card-body">
            <div class="row">
                {% if username1 is none %}
                    <div class="col-lg-12">
                        <div class="list-group">
                            {% for user in users %}
                                <a class="list-group-item" href="{% url 'main:matrix1' user.name %}">
                                    {{ user.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    {% for r in result %}
                        <div class="col-lg-4">
                            <h4 class="white">{{ r.username1 }}</h4>
                            <p class="white">
                                {% for c in r.user1_courses %}
                                    {{ c }},
                                {% endfor %}
                            </p>
                        </div>
                        <div class="col-lg-4">
                            <h4 class="white">{{ r.username2 }}</h4>
                            <p class="white">
                                {% for c in r.user2_courses %}
                                    {{ c }},
                                {% endfor %}
                            </p>
                        </div>
                        <div class="col-lg-4">
                            <h1 class="white">{{ r.coef }}</h1>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

main/templates/recommendations_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Recommendations</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/select_course.css' %}">
    <style>
        .white {
            color: white;
        }
    </style>
</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>Таблица результатов</h4>
        </div>

        <div class="card-body">
            <ul class="list-group">
                {% if users %}
                    {% for user in users %}
                        <a href="{% url 'main:show_recommendations' user.name %}" class="list-group-item">{{ user.name }}</a>
                    {% endfor %}
                {% else %}
                    {% for key, value in recommendations.items %}
                        <li class="list-group-item"><b>{{ key }}</b> <small>(кол-во совпадений {{ value }})</small></li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
</div>
</body>
</html>

main/templates/result_table.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/select_course.css' %}">
    <style>
        .white {
            color: white;
        }
    </style>
</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>Таблица результатов</h4>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-condensed table-hover white">
                <tr class="text-center">
                    <td></td>
                    {% for course in courses %}
                        <th>{{ course.name }}</th>
                    {% endfor %}
                </tr>
                {% for user in users %}
                    <tr>
                        <th>{{ user.name }}</th>
                        {% for course in courses %}
                            <td class="text-center">
                                {% for us in course.users.all %}
                                    {% if us.id == user.id %}
                                        +
                                    {% endif %}
                                {% endfor %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
</body>
</html>

main/templates/select_course.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Select courses</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/select_course.css' %}">
</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>Выберите интересные вам курсы</h4>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="mess">
                        {% if mess %}
                            <div id="bs-success" class="alert alert-success">
                                {{ mess }}
                            </div>
                        {% endif %}
                    </div>
                    <form class="form-row" method="post" action="{% url 'main:select_courses' username %}">
                        {% csrf_token %}
                        {% for course in courses %}
                            <div class="form-check">
                                <input style="color: white" class="form-check-input" type="checkbox"
                                       name="selected_courses" value="{{ course.id }}" id="{{ course.name }}"
                                    {% if course.id in selected_cources_ids %}
                                        checked
                                   {% endif %}
                                >
                                <label for="{{ course.name }}">{{ course.name }}</label><br/>
                            </div>
                        {% endfor %}

                        <input type="submit" id="calculate" class="btn btn-md btn-warning" value="Сохранить">
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

main/templates/select_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'recommendations/select_course.css' %}">
    <style>
        .white {
            color: white;
        }
    </style>
</head>
<body>
{% include 'common/navbar.html' %}
<div class="container">
    <div class="card border-warning">
        <div class="card-header text-white">
            <h4>Вход</h4>
        </div>

        <div class="card-body">
            {% if error_mess %}
                <h2 class="white">{{ error_mess }}</h2>
            {% endif %}
            <form method="post" action="{% url 'main:select_user' %}">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <select name="name" class="form-control">
                        <option value="">Выбрать пользователя</option>
                        {% for user in users %}
                            <option value="{{ user.name }}">{{ user.name }}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit" id="button-addon1">Войти</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>